import React,{useEffect,useRef,useState}from'react';
import{Code2,Heading1,Heading2,Heading3,Heading4,Heading5,Heading6,List,ListChecks,ListOrdered,Minus,Pilcrow,Quote,ChevronsDownUp,Redo2,Undo2,Check,SendHorizontal,Trash2,Plus,MinusCircle,Bold,Italic,Underline,Strikethrough,EyeOff,Code,Highlighter,Subscript,Superscript,Link,Mail,Phone,AtSign,Hash,DollarSign,Terminal,Clock3,CreditCard,Smile,Type}from'lucide-react';
import{createInitialDocument}from'../document/schema.js';import{changeType,mergePrevious,removeBlock,splitListItem,splitTextBlock,updateListItem,removeListItem,ensureEditableNeighbors,promoteEmptyParagraphToSpacing,updateSpacing}from'../document/operations.js';import{createHistory,record,redo,undo}from'../document/history.js';import{serializeDocument}from'../telegram/serializer.js';import{telegramHaptic}from'../telegram/webApp.js';

function htmlEscape(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function editorHtml(v){const s=String(v||'');return /<(b|strong|i|em|u|ins|s|strike|del|code|mark|sub|sup|a|span)\b/i.test(s)?s:htmlEscape(s);}
function plainText(v){return String(v||'').replace(/<[^>]*>/g,'');}
function selectionOffset(node){const s=getSelection();if(!s?.rangeCount)return plainText(node.innerHTML).length;const r=s.getRangeAt(0),p=r.cloneRange();p.selectNodeContents(node);p.setEnd(r.startContainer,r.startOffset);return p.toString().length}
function focus(id,offset=0){requestAnimationFrame(()=>{const node=document.querySelector('[data-editor-id="'+CSS.escape(id)+'"]');if(!node)return;node.focus();const r=document.createRange(),w=document.createTreeWalker(node,NodeFilter.SHOW_TEXT);let n,left=offset;r.selectNodeContents(node);r.collapse(true);while((n=w.nextNode())){if(left<=n.length){r.setStart(n,left);r.collapse(true);break}left-=n.length}const s=getSelection();s.removeAllRanges();s.addRange(r)})}
function Editable({id,text,placeholder,className='',onChange,onKeyDown}){const ref=useRef(null);React.useEffect(()=>{const node=ref.current;if(!node)return;const next=editorHtml(text);if(node.innerHTML!==next&&node.textContent!==plainText(text))node.innerHTML=next},[text]);return <div ref={n=>{ref.current=n;if(n&&!n.textContent)n.innerHTML=editorHtml(text)}} data-editor-id={id} className={'editable '+className} contentEditable suppressContentEditableWarning data-placeholder={placeholder} data-placeholder-visible={plainText(text)?'false':'true'} onInput={e=>onChange(e.currentTarget.innerHTML)} onKeyDown={e=>onKeyDown?.(e,e.currentTarget)}/>}


const menuItems=[
 {type:'paragraph',label:'Paragraph',Icon:Pilcrow},
 {type:'heading',size:1,label:'Heading 1',Icon:Heading1},{type:'heading',size:2,label:'Heading 2',Icon:Heading2},{type:'heading',size:3,label:'Heading 3',Icon:Heading3},{type:'heading',size:4,label:'Heading 4',Icon:Heading4},{type:'heading',size:5,label:'Heading 5',Icon:Heading5},{type:'heading',size:6,label:'Heading 6',Icon:Heading6},
 {divider:true},
 {type:'pre',label:'Code block',Icon:Code2},{type:'footer',label:'Footer',Icon:Pilcrow},{type:'blockquote',label:'Blockquote',Icon:Quote},{type:'expandable_blockquote',label:'Expandable blockquote',Icon:ChevronsDownUp},{type:'pullquote',label:'Pullquote',Icon:Quote},
 {divider:true},
 {type:'list-bullet',label:'Bulleted list',Icon:List},{type:'list-number',label:'Numbered list',Icon:ListOrdered},{type:'list-checklist',label:'Checklist',Icon:ListChecks},{type:'divider',label:'Divider',Icon:Minus}
];
const inlineItems=[
 {type:'regular',label:'Regular',Icon:Type},{divider:true},
 {type:'bold',label:'Bold',Icon:Bold},{type:'italic',label:'Italic',Icon:Italic},{type:'underline',label:'Underline',Icon:Underline},{type:'strikethrough',label:'Strikethrough',Icon:Strikethrough},
 {type:'spoiler',label:'Spoiler',Icon:EyeOff},{type:'code',label:'Inline code',Icon:Code},{type:'marked',label:'Marked',Icon:Highlighter},{type:'subscript',label:'Subscript',Icon:Subscript},{type:'superscript',label:'Superscript',Icon:Superscript},
 {divider:true},{type:'url',label:'URL',Icon:Link},{type:'email_address',label:'Email',Icon:Mail},{type:'phone_number',label:'Phone',Icon:Phone},{type:'mention',label:'Mention',Icon:AtSign},
 {type:'hashtag',label:'Hashtag',Icon:Hash},{type:'cashtag',label:'Cashtag',Icon:DollarSign},{type:'bot_command',label:'Bot command',Icon:Terminal},{type:'date_time',label:'Date & time',Icon:Clock3},{type:'bank_card_number',label:'Bank card',Icon:CreditCard},{type:'custom_emoji',label:'Custom emoji',Icon:Smile}
];


function unwrapIntersecting(node,range){[...node.querySelectorAll('[data-rich]')].reverse().forEach(el=>{try{if(!range.intersectsNode(el))return;const p=el.parentNode;if(!p)return;while(el.firstChild)p.insertBefore(el.firstChild,el);p.removeChild(el)}catch{}})}
function wrapSelection(node,tag,attrs={}){const s=getSelection();if(!s?.rangeCount||s.isCollapsed)return false;const r=s.getRangeAt(0).cloneRange(),el=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));try{el.appendChild(r.extractContents());r.insertNode(el);s.removeAllRanges();s.addRange(r);return true}catch{return false}}
function applyInlineCommand(node,type){if(!node)return;node.focus();const s=getSelection();if(!s?.rangeCount||s.isCollapsed)return;const range=s.getRangeAt(0).cloneRange();
if(type==='regular'){document.execCommand('removeFormat',false,null);unwrapIntersecting(node,range)}
else if(['bold','italic','underline','strikethrough','subscript','superscript'].includes(type)){document.execCommand(type==='strikethrough'?'strikeThrough':type,false,null)}
else if(type==='spoiler')wrapSelection(node,'span',{'class':'tg-spoiler','data-rich':'spoiler'})
else if(type==='marked')wrapSelection(node,'mark',{'data-rich':'marked'})
else if(type==='code')wrapSelection(node,'code',{'data-rich':'code'})
else if(['mention','hashtag','cashtag','bot_command'].includes(type))wrapSelection(node,'span',{'data-rich':type})
else if(['url','email_address','phone_number','bank_card_number'].includes(type)){const value=window.prompt(type==='url'?'URL':type==='email_address'?'Email address':type==='phone_number'?'Phone number':'Bank card number');if(!value)return;if(type==='url')wrapSelection(node,'a',{href:value});else wrapSelection(node,'span',{'data-rich':type,'data-value':value})}
else if(type==='date_time'){const unix=window.prompt('Unix time',String(Math.floor(Date.now()/1000)));if(!unix)return;const format=window.prompt('Format (r, w, d, D, t, T or combination)','wDT')??'';wrapSelection(node,'span',{'data-rich':'date_time','data-unix':unix,'data-format':format})}
else if(type==='custom_emoji'){const id=window.prompt('Custom emoji ID');if(!id)return;wrapSelection(node,'span',{'data-rich':'custom_emoji','data-id':id})}
else if(type==='mathematical_expression'){const expression=window.prompt('LaTeX expression');if(!expression)return;wrapSelection(node,'span',{'data-rich':'mathematical_expression','data-expression':expression})}
node.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'formatInline'}))}
function splitEditorBlock(doc,block,node){const s=getSelection();if(!s?.rangeCount)return null;const r=s.getRangeAt(0),start=r.cloneRange(),end=r.cloneRange(),a=document.createElement('div'),z=document.createElement('div');start.selectNodeContents(node);start.setEnd(r.startContainer,r.startOffset);end.selectNodeContents(node);end.setStart(r.endContainer,r.endOffset);a.appendChild(start.cloneContents());z.appendChild(end.cloneContents());const right=z.innerHTML,next={id:crypto.randomUUID(),type:'paragraph',text:right,structural:!plainText(right).trim()},blocks=doc.blocks.map(x=>x.id===block.id?{...x,text:a.innerHTML}:x),i=blocks.findIndex(x=>x.id===block.id);blocks.splice(i+1,0,next);return{doc:{...doc,blocks},nextId:next.id}}
function inlineMenu(){return <div className="format-menu inline-format-menu" role="menu">{inlineItems.map((item,i)=>item.divider?<div className="format-divider" key={'id'+i}/>:<button key={item.type} role="menuitem" onMouseDown={e=>e.preventDefault()} onClick={()=>{applyInlineCommand(document.querySelector('[data-editor-id="'+CSS.escape(active||'')+'"]'),item.type);setInlineOpen(false);telegramHaptic('light')}}><item.Icon size={18}/><span>{item.label}</span></button>)}</div>}
export default function RichEditor({onSend}){const[doc,setDoc]=useState(createInitialDocument),[active,setActive]=useState(null),[open,setOpen]=useState(false),[inlineOpen,setInlineOpen]=useState(false),history=useRef(createHistory())
const hasContent=doc.blocks.some(b=>{if(b.type==='list')return b.items?.some(i=>plainText(i.text).trim());if(b.type==='divider')return true;return plainText(b.text).trim()});
function commit(next,focusTarget=null,opts={}){const blocks=[];next.blocks.forEach((b,i)=>{blocks.push(b);if(b.type==='spacing'&&next.blocks[i+1]?.type!=='paragraph')blocks.push({id:crypto.randomUUID(),type:'paragraph',text:'',structural:true})});const normalized=blocks.length===next.blocks.length?next:{...next,blocks};record(history.current,doc,opts);setDoc(normalized);if(focusTarget)focus(focusTarget.id,focusTarget.offset||0)}
function textChange(id,text){commit({...doc,blocks:doc.blocks.map(b=>b.id===id?{...b,text}:b)},null,{coalesce:true})}
function key(block,e,node){const off=selectionOffset(node);setActive(block.id);if(e.key==='Enter'){if(block.type==='blockquote'||block.type==='expandable_blockquote'||block.type==='pullquote')return;e.preventDefault();if(block.type==='paragraph'&&!String(block.text||'').trim()){const r=promoteEmptyParagraphToSpacing(doc,block.id);if(r.nextId){commit(r.doc,{id:r.nextId});setActive(r.nextId);telegramHaptic('light')}return}const r=splitEditorBlock(doc,block,node)||splitTextBlock(doc,block.id,off);if(r.nextId)commit(r.doc,{id:r.nextId});return}if(e.key==='Backspace'&&off===0){e.preventDefault();if(block.structural){const i=doc.blocks.findIndex(x=>x.id===block.id),prev=doc.blocks[i-1];if(prev?.intentionalEmpty){commit(removeBlock(doc,prev.id),{id:block.id});telegramHaptic('light');return}}const r=mergePrevious(doc,block.id);if(r.doc!==doc)commit(r.doc,{id:r.focusId,offset:r.offset})}}
function listKey(block,item,index,e,node){const off=caret(node);if(e.key==='Enter'){e.preventDefault();if(!item.text&&index===block.items.length-1){commit(removeBlock(doc,block.id));return}const r=splitListItem(doc,block.id,item.id,off);commit(r.doc,{id:r.nextItemId})}else if(e.key==='Backspace'&&off===0&&!item.text&&block.items.length>1){e.preventDefault();commit(removeListItem(doc,block.id,item.id))}}
function deleteBlock(id){const index=doc.blocks.findIndex(b=>b.id===id);if(index<0)return;const next=removeBlock(doc,id);const target=next.blocks[index]||next.blocks[index-1]||next.blocks[0];commit(next);setActive(target?.id||null);telegramHaptic('light')}
function type(kind,o={}){const id=active||doc.blocks[0].id;const t=kind.startsWith('list-')?'list':kind;const style=kind==='list-number'?'number':kind==='list-checklist'?'checklist':'bullet';let next=changeType(doc,id,t,t==='list'?{style}:o);if(t!=='heading'&&t!=='paragraph')next=ensureEditableNeighbors(next,id);commit(next,{id});setOpen(false);telegramHaptic('light')}
function inlineMenu(){return <div className="format-menu inline-format-menu" role="menu">{inlineItems.map((item,i)=>item.divider?<div className="format-divider" key={'id'+i}/>:<button key={item.type} role="menuitem" onMouseDown={e=>e.preventDefault()} onClick={()=>{applyInlineCommand(document.querySelector('[data-editor-id="'+CSS.escape(active||'')+'"]'),item.type);setInlineOpen(false);telegramHaptic('light')}}><item.Icon size={18}/><span>{item.label}</span></button>)}</div>}
function menu(){const activeBlock=doc.blocks.find(b=>b.id===active)||doc.blocks[0];return <div className="format-menu" role="menu">{menuItems.map((item,i)=>item.divider?<div className="format-divider" key={'d'+i}/>:<button key={item.type+(item.size||'')} className={activeBlock?.type===item.type&&(!item.size||activeBlock?.size===item.size)?'selected':''} role="menuitem" onClick={()=>type(item.type,{size:item.size})}><item.Icon size={19}/><span>{item.label}</span>{activeBlock?.type===item.type&&(!item.size||activeBlock?.size===item.size)&&<Check size={17} className="menu-check"/>}</button>)}</div>}
function updateCredit(id,credit){commit({...doc,blocks:doc.blocks.map(b=>b.id===id?{...b,credit}:b)},null,{coalesce:true})}
function quoteKey(block,e,node){if(e.key!=='Backspace'||node.selectionStart!==0)return;e.preventDefault();const r=mergePrevious(doc,block.id);if(r.doc!==doc)commit(r.doc,{id:r.focusId,offset:r.offset})}
function resizeQuote(node){if(!node)return;node.style.height='auto';node.style.height=Math.max(27,node.scrollHeight)+'px'}
function creditKey(e){if(e.key==='Enter'){e.preventDefault()}}
function block(b){const canDelete=active===b.id;const del=<button type="button" className="block-delete" aria-label={`Delete ${b.type}`} onMouseDown={e=>e.preventDefault()} onClick={e=>{e.stopPropagation();deleteBlock(b.id)}}><Trash2 size={16}/></button>;if(b.type==='divider')return <div key={b.id} className="editor-block divider-editor-block" onClick={()=>setActive(b.id)}>{canDelete&&del}<div className="divider-block"/></div>;if(b.type==='pre')return <div key={b.id} className="editor-block pre-editor-block" onFocus={()=>setActive(b.id)}>{canDelete&&del}<div className="pre-wrap"><textarea data-editor-id={b.id} value={b.text} placeholder="Code…" onFocus={()=>setActive(b.id)} onChange={e=>commit({...doc,blocks:doc.blocks.map(x=>x.id===b.id?{...x,text:e.target.value}:x)})}/><select value={b.language} onChange={e=>commit({...doc,blocks:doc.blocks.map(x=>x.id===b.id?{...x,language:e.target.value}:x)})}><option value="">Plain text</option>{['javascript','typescript','python','html','css','json','bash','sql','java','c','cpp','csharp','go','rust','php','kotlin','swift','xml','yaml','markdown'].map(x=><option key={x} value={x}>{x}</option>)}</select></div></div>;if(b.type==='list')return <div className="editor-block list-editor-block" key={b.id} onFocus={()=>setActive(b.id)}>{canDelete&&del}<div className="list-block">{b.items.map((i,n)=><div className="list-item" key={i.id}><span className="marker">{b.style==='number'?n+1+'.':b.style==='checklist'?<input type="checkbox" checked={!!i.checked} onChange={e=>commit(updateListItem(doc,b.id,i.id,{checked:e.target.checked}))}/>: '•'}</span><Editable id={i.id} text={i.text} placeholder="List item" className="list-editable" onChange={t=>commit(updateListItem(doc,b.id,i.id,{text:t}),null,{coalesce:true})} onKeyDown={(e,n)=>listKey(b,i,n,e,n)}/></div>)}</div></div>;
const common={id:b.id,text:b.text,placeholder:b.structural?'Write something…':b.type==='heading'?`Heading ${b.size}`:b.type==='footer'?'Footer':b.type==='blockquote'||b.type==='expandable_blockquote'||b.type==='pullquote'?'Quote':'Write something…',className:b.type==='heading'?'heading h-'+b.size:b.type==='footer'?'footer':b.type==='blockquote'?'blockquote-text':b.type==='expandable_blockquote'?'expandable-blockquote-text':b.type==='pullquote'?'pullquote-text':'',onChange:t=>textChange(b.id,t),onKeyDown:(e,n)=>key(b,e,n)};if(b.type==='spacing')return <div key={b.id} className={'editor-block spacing-editor-block '+(active===b.id?'active':'')} onClick={()=>setActive(b.id)}>{canDelete&&del}<div className="spacing-control" onClick={e=>e.stopPropagation()}><button type="button" aria-label="Decrease spacing" disabled={b.lines<=1} onClick={()=>commit(updateSpacing(doc,b.id,b.lines-1))}><MinusCircle size={18}/></button><span>{b.lines} {b.lines===1?'line':'lines'}</span><button type="button" aria-label="Increase spacing" disabled={b.lines>=8} onClick={()=>commit(updateSpacing(doc,b.id,b.lines+1))}><Plus size={18}/></button></div></div>;return <div key={b.id} className={'editor-block text-editor-block '+(b.type==='blockquote'?'blockquote-editor-block ':b.type==='expandable_blockquote'?'expandable-blockquote-editor-block ':b.type==='pullquote'?'pullquote-editor-block ':'')+(active===b.id?'active':'')} onFocus={()=>setActive(b.id)}>{canDelete&&del}{(b.type==='blockquote'||b.type==='expandable_blockquote'||b.type==='pullquote')?<textarea data-editor-id={b.id} className={'editable quote-editable '+(b.type==='pullquote'?'pullquote-text':b.type==='expandable_blockquote'?'expandable-blockquote-text':'blockquote-text')} value={b.text||''} placeholder={common.placeholder} rows={1} spellCheck enterKeyHint="enter" autoCapitalize="sentences" onFocus={e=>{setActive(b.id);resizeQuote(e.currentTarget)}} onInput={e=>resizeQuote(e.currentTarget)} onChange={e=>textChange(b.id,e.target.value)} onKeyDown={e=>quoteKey(b,e,e.currentTarget)}/>:<>{!String(b.text||'').length&&<span className={'editor-placeholder '+common.className} aria-hidden="true">{common.placeholder}</span>}<Editable {...common}/></>}{(b.type==='blockquote'||b.type==='expandable_blockquote'||b.type==='pullquote')&&<div className={'quote-credit-wrap '+(b.type==='pullquote'?'pullquote-credit':b.type==='expandable_blockquote'?'expandable-blockquote-credit':'blockquote-credit')}><div className="quote-credit-field">{!String(b.credit||'').length&&<span className="quote-credit-placeholder" aria-hidden="true">Credit (optional)</span>}<Editable id={b.id+'-credit'} text={b.credit||''} placeholder="" className="quote-credit" onChange={t=>updateCredit(b.id,t)} onKeyDown={creditKey}/></div></div>}</div>}
return <div className="editor-shell"><div className="topbar"><button className="icon-button history-button" disabled={!history.current.past.length} onClick={()=>{const n=undo(history.current,doc);if(n){setDoc(n);telegramHaptic('light')}}} aria-label="Undo"><Undo2 size={19}/></button><button className="icon-button history-button" disabled={!history.current.future.length} onClick={()=>{const n=redo(history.current,doc);if(n){setDoc(n);telegramHaptic('light')}}} aria-label="Redo"><Redo2 size={19}/></button></div><main className="document-area">{doc.blocks.map(block)}</main><div className="composer-bar"><div className="format-wrap"><button className={'tool-button format-button '+(open?'active':'')} onClick={()=>{setOpen(x=>!x);setInlineOpen(false);telegramHaptic('light')}} aria-label="Block type" aria-expanded={open}><span className="heading-glyph">H</span></button>{open&&menu()}</div><div className="format-wrap"><button className={'tool-button format-button '+(inlineOpen?'active':'')} onMouseDown={e=>e.preventDefault()} onClick={()=>{setInlineOpen(x=>!x);setOpen(false);telegramHaptic('light')}} aria-label="Inline formatting" aria-expanded={inlineOpen}><span className="bold-glyph">B</span></button>{inlineOpen&&inlineMenu()}</div><button className={'send-composer-button '+(hasContent?'visible':'')} onClick={()=>{if(!hasContent)return;telegramHaptic('light');onSend?.(doc)}} aria-label="Send rich message" aria-hidden={!hasContent} tabIndex={hasContent?0:-1} disabled={!hasContent}><SendHorizontal size={20}/></button></div></div>}
export {serializeDocument};
