import React,{useEffect,useRef,useState}from'react';
import{Code2,Heading1,Heading2,Heading3,Heading4,Heading5,Heading6,List,ListChecks,ListOrdered,Minus,Paragraph,Quote,Redo2,Undo2,Check}from'lucide-react';
import{createInitialDocument}from'../document/schema.js';import{changeType,mergePrevious,removeBlock,splitListItem,splitTextBlock,updateListItem,removeListItem}from'../document/operations.js';import{createHistory,record,redo,undo}from'../document/history.js';import{serializeDocument}from'../telegram/serializer.js';import{configureTelegramMainButton,setTelegramMainButton,telegramHaptic}from'../telegram/webApp.js';

function caret(node){const s=getSelection();if(!s?.rangeCount)return(node.textContent||'').length;const r=s.getRangeAt(0),p=r.cloneRange();p.selectNodeContents(node);p.setEnd(r.startContainer,r.startOffset);return p.toString().length}
function focus(id,offset=0){requestAnimationFrame(()=>{const node=document.querySelector('[data-editor-id="'+CSS.escape(id)+'"]');if(!node)return;node.focus();const r=document.createRange(),w=document.createTreeWalker(node,NodeFilter.SHOW_TEXT);let n,left=offset;r.selectNodeContents(node);r.collapse(true);while((n=w.nextNode())){if(left<=n.length){r.setStart(n,left);r.collapse(true);break}left-=n.length}const s=getSelection();s.removeAllRanges();s.addRange(r)})}
function Editable({id,text,placeholder,className='',onChange,onKeyDown}){const ref=useRef(null);const last=useRef(text);React.useEffect(()=>{if(ref.current&&document.activeElement!==ref.current&&last.current!==text){ref.current.textContent=text;last.current=text}},[text]);return <div ref={n=>{ref.current=n;if(n&&n.textContent!==text&&!n.isContentEditable)n.textContent=text}} data-editor-id={id} className={'editable '+className} contentEditable suppressContentEditableWarning data-placeholder={placeholder} onInput={e=>{last.current=e.currentTarget.textContent||'';onChange(last.current)}} onKeyDown={e=>onKeyDown?.(e,e.currentTarget)}/>}

const menuItems=[
 {type:'paragraph',label:'Paragraph',Icon:Paragraph},
 {type:'heading',size:1,label:'Heading 1',Icon:Heading1},{type:'heading',size:2,label:'Heading 2',Icon:Heading2},{type:'heading',size:3,label:'Heading 3',Icon:Heading3},{type:'heading',size:4,label:'Heading 4',Icon:Heading4},{type:'heading',size:5,label:'Heading 5',Icon:Heading5},{type:'heading',size:6,label:'Heading 6',Icon:Heading6},
 {divider:true},
 {type:'pre',label:'Code block',Icon:Code2},{type:'footer',label:'Footer',Icon:Paragraph},{type:'blockquote',label:'Blockquote',Icon:Quote},{type:'pullquote',label:'Pullquote',Icon:Quote},
 {divider:true},
 {type:'list-bullet',label:'Bulleted list',Icon:List},{type:'list-number',label:'Numbered list',Icon:ListOrdered},{type:'list-checklist',label:'Checklist',Icon:ListChecks},{type:'divider',label:'Divider',Icon:Minus}
];

export default function RichEditor({onSend}){const[doc,setDoc]=useState(createInitialDocument),[active,setActive]=useState(null),[open,setOpen]=useState(false),history=useRef(createHistory()),mainClick=useRef(null);
const hasContent=doc.blocks.some(b=>{if(b.type==='list')return b.items?.some(i=>String(i.text||'').trim());if(b.type==='divider')return true;return String(b.text||'').trim()});
function commit(next,focusTarget=null,opts={}){record(history.current,doc,opts);setDoc(next);if(focusTarget)focus(focusTarget.id,focusTarget.offset||0)}
function textChange(id,text){commit({...doc,blocks:doc.blocks.map(b=>b.id===id?{...b,text}:b)},null,{coalesce:true})}
function key(block,e,node){const off=caret(node);setActive(block.id);if(e.key==='Enter'){e.preventDefault();const r=splitTextBlock(doc,block.id,off);if(r.nextId)commit(r.doc,{id:r.nextId});return}if(e.key==='Backspace'&&off===0){e.preventDefault();const r=mergePrevious(doc,block.id);if(r.doc!==doc)commit(r.doc,{id:r.focusId,offset:r.offset})}}
function listKey(block,item,index,e,node){const off=caret(node);if(e.key==='Enter'){e.preventDefault();if(!item.text&&index===block.items.length-1){commit(removeBlock(doc,block.id));return}const r=splitListItem(doc,block.id,item.id,off);commit(r.doc,{id:r.nextItemId})}else if(e.key==='Backspace'&&off===0&&!item.text&&block.items.length>1){e.preventDefault();commit(removeListItem(doc,block.id,item.id))}}
function type(kind,o={}){const id=active||doc.blocks[0].id;const t=kind.startsWith('list-')?'list':kind;const style=kind==='list-number'?'number':kind==='list-checklist'?'checklist':'bullet';commit(changeType(doc,id,t,t==='list'?{style}:o));setOpen(false);telegramHaptic('light')}
function menu(){const activeBlock=doc.blocks.find(b=>b.id===active)||doc.blocks[0];return <div className="format-menu" role="menu">{menuItems.map((item,i)=>item.divider?<div className="format-divider" key={'d'+i}/>:<button key={item.type+(item.size||'')} className={activeBlock?.type===item.type&&(!item.size||activeBlock?.size===item.size)?'selected':''} role="menuitem" onClick={()=>type(item.type,{size:item.size})}><item.Icon size={19}/><span>{item.label}</span>{activeBlock?.type===item.type&&(!item.size||activeBlock?.size===item.size)&&<Check size={17} className="menu-check"/>}</button>)}</div>}
function block(b){if(b.type==='divider')return <div key={b.id} className="divider-block" onClick={()=>setActive(b.id)}/>;if(b.type==='pre')return <div key={b.id} className="pre-wrap"><textarea value={b.text} placeholder="Code…" onFocus={()=>setActive(b.id)} onChange={e=>commit({...doc,blocks:doc.blocks.map(x=>x.id===b.id?{...x,text:e.target.value}:x)},{id:b.id})}/><select value={b.language} onChange={e=>commit({...doc,blocks:doc.blocks.map(x=>x.id===b.id?{...x,language:e.target.value}:x)})}><option value="">Plain text</option>{['javascript','typescript','python','html','css','json','bash','sql','java','c','cpp','csharp','go','rust','php','kotlin','swift','xml','yaml','markdown'].map(x=><option key={x} value={x}>{x}</option>)}</select></div>;if(b.type==='list')return <div className="list-block" key={b.id}>{b.items.map((i,n)=><div className="list-item" key={i.id}><span className="marker">{b.style==='number'?n+1+'.':b.style==='checklist'?<input type="checkbox" checked={!!i.checked} onChange={e=>commit(updateListItem(doc,b.id,i.id,{checked:e.target.checked}))}/>: '•'}</span><Editable id={i.id} text={i.text} placeholder="List item" className="list-editable" onChange={t=>commit(updateListItem(doc,b.id,i.id,{text:t}),null,{coalesce:true})} onKeyDown={(e,n)=>listKey(b,i,n,e,n)}/></div>)}</div>;
const common={id:b.id,text:b.text,placeholder:b.type==='heading'?'Heading':b.type==='footer'?'Footer':b.type==='blockquote'||b.type==='pullquote'?'Quote':'Write something…',className:b.type==='heading'?'heading h-'+b.size:b.type==='footer'?'footer':b.type==='blockquote'?'blockquote-text':b.type==='pullquote'?'pullquote-text':'',onChange:t=>textChange(b.id,t),onKeyDown:(e,n)=>key(b,e,n)};return <div key={b.id} onFocus={()=>setActive(b.id)}>{<Editable {...common}/>}</div>}
useEffect(()=>{const cleanup=configureTelegramMainButton({onClick:()=>{if(!hasContent)return;telegramHaptic('light');onSend?.(doc)}});return cleanup},[onSend,doc,hasContent]);
useEffect(()=>{setTelegramMainButton({visible:hasContent&&!open,text:'Send',active:hasContent});return()=>setTelegramMainButton({visible:false})},[hasContent,open]);
useEffect(()=>()=>setTelegramMainButton({visible:false}),[]);
return <div className="editor-shell"><div className="topbar"><button className="icon-button history-button" disabled={!history.current.past.length} onClick={()=>{const n=undo(history.current,doc);if(n){setDoc(n);telegramHaptic('light')}}} aria-label="Undo"><Undo2 size={19}/></button><button className="icon-button history-button" disabled={!history.current.future.length} onClick={()=>{const n=redo(history.current,doc);if(n){setDoc(n);telegramHaptic('light')}}} aria-label="Redo"><Redo2 size={19}/></button></div><main className="document-area">{doc.blocks.map(block)}</main><div className="composer-bar"><div className="format-wrap"><button className={'tool-button format-button '+(open?'active':'')} onClick={()=>{setOpen(x=>!x);telegramHaptic('light')}} aria-label="Block type" aria-expanded={open}><span className="heading-glyph">H</span></button>{open&&menu()}</div></div></div>}
export {serializeDocument};
