const INDEX='rich_channels_index',PREFIX='rich_channel_',DEFAULT='rich_default_channel';
const app=()=>typeof window!=='undefined'?window.Telegram?.WebApp??null:null;
function cloud(){const value=app()?.CloudStorage;if(!value?.getItem||!value?.setItem)return null;return value;}
function call(method,...args){const storage=cloud();return new Promise((resolve,reject)=>{if(!storage?.[method])return reject(new Error('Telegram CloudStorage is unavailable. Please open the Mini App in the latest Telegram app.'));storage[method](...args,(error,value)=>error?reject(new Error(error)):resolve(value));});}
export async function loadChannels(){const raw=await call('getItem',INDEX);const ids=(()=>{try{return JSON.parse(raw||'[]')||[]}catch{return[]}})();if(!ids.length)return[];const values=await call('getItems',ids.map(id=>PREFIX+id));return ids.map(id=>values?.[PREFIX+id]).filter(Boolean).map(v=>{try{return JSON.parse(v)}catch{return null}}).filter(Boolean);}
export async function saveChannel(channel){const old=await loadChannels(),ids=old.map(x=>String(x.id));if(!ids.includes(String(channel.id)))ids.push(String(channel.id));await call('setItem',INDEX,JSON.stringify(ids));await call('setItem',PREFIX+channel.id,JSON.stringify(channel));return[...old.filter(x=>String(x.id)!==String(channel.id)),channel];}
export async function removeChannel(id){const old=await loadChannels(),ids=old.map(x=>String(x.id)).filter(x=>x!==String(id));await call('setItem',INDEX,JSON.stringify(ids));await call('removeItem',PREFIX+id);const next=old.filter(x=>String(x.id)!==String(id));if(String(await loadDefaultChannel())===String(id))await saveDefaultChannel(next[0]?.id||'');return next;}
export async function loadDefaultChannel(){return(await call('getItem',DEFAULT))||'';}
export async function saveDefaultChannel(id){await call('setItem',DEFAULT,String(id||''));}
