export function getTelegramWebApp(){return typeof window!=='undefined'?window.Telegram?.WebApp??null:null;}
export function initTelegramWebApp(){const app=getTelegramWebApp();if(!app)return null;app.ready();app.expand();app.setHeaderColor?.('bg_color');app.setBackgroundColor?.('bg_color');return app;}
export function getTelegramUser(){return getTelegramWebApp()?.initDataUnsafe?.user??null;}
export function configureTelegramNavigation({onBack,onSettings}){const app=getTelegramWebApp();if(!app)return()=>{};const back=()=>onBack?.(),settings=()=>onSettings?.();app.BackButton?.onClick?.(back);app.SettingsButton?.onClick?.(settings);return()=>{app.BackButton?.offClick?.(back);app.SettingsButton?.offClick?.(settings);};}
export function setTelegramNavigation({showBack=false,showSettings=false}={}){const app=getTelegramWebApp();if(!app)return;showBack?app.BackButton?.show?.():app.BackButton?.hide?.();showSettings?app.SettingsButton?.show?.():app.SettingsButton?.hide?.();}
export function telegramHaptic(type='success'){getTelegramWebApp()?.HapticFeedback?.notificationOccurred?.(type);}
export function telegramImpact(style='light'){getTelegramWebApp()?.HapticFeedback?.impactOccurred?.(style);}
export function telegramPopup({title='Confirm action',message,buttons}){const app=getTelegramWebApp();return new Promise(resolve=>{if(!app?.showPopup){app?.showConfirm?.(message||'',ok=>resolve(Boolean(ok)));return}app.showPopup({title,message,buttons},id=>resolve(id));});}
export function configureTelegramMainButton({onClick,onVisibilityChange}={}){const app=getTelegramWebApp(),button=app?.MainButton;if(!app||!button)return()=>{};const click=()=>onClick?.();const changed=()=>onVisibilityChange?.(button.isVisible);if(app.onEvent)app.onEvent('mainButtonClicked',click);else button.onClick?.(click);if(onVisibilityChange)app.onEvent?.('viewportChanged',changed);return()=>{if(app.offEvent)app.offEvent('mainButtonClicked',click);else button.offClick?.(click);if(onVisibilityChange)app.offEvent?.('viewportChanged',changed);};}
export function setTelegramMainButton({visible=false,text='Send',active=true,progress=false,shine=false}={}){const button=getTelegramWebApp()?.MainButton;if(!button)return;if(progress)button.showProgress?.();else button.hideProgress?.();button.setParams?.({text,is_visible:visible,is_active:active,has_shine_effect:shine});}
