import {createBlock} from './schema.js';
const idx=(d,id)=>d.blocks.findIndex(b=>b.id===id);
export function replaceBlock(d,id,fn){return{...d,blocks:d.blocks.map(b=>b.id===id?fn(b):b)};}
export function insertAfter(d,id,b){const i=idx(d,id);if(i<0)return d;const blocks=[...d.blocks];blocks.splice(i+1,0,b);return{...d,blocks};}
export function removeBlock(d,id){if(d.blocks.length<=1)return{...d,blocks:[createBlock('paragraph')]};return{...d,blocks:d.blocks.filter(b=>b.id!==id)};}
export function splitTextBlock(d,id,offset){const b=d.blocks.find(x=>x.id===id);if(!b||!['paragraph','heading','footer','blockquote','expandable_blockquote','pullquote'].includes(b.type))return{doc:d,nextId:null};const right=b.text.slice(offset),n=createBlock('paragraph',{text:right,structural:!right.trim()});return{doc:replaceBlock(insertAfter(d,id,n),id,x=>({...x,text:x.text.slice(0,offset),intentionalEmpty:false})),nextId:n.id};}
export function promoteEmptyParagraphToSpacing(d,id){const b=d.blocks.find(x=>x.id===id);if(!b||b.type!=='paragraph'||String(b.text||'').trim())return{doc:d,nextId:null};const spacing=createBlock('spacing',{lines:1});const helper=createBlock('paragraph',{structural:true});const withSpacing=replaceBlock(d,id,()=>spacing);return{doc:insertAfter(withSpacing,id,helper),nextId:helper.id};}
export function updateSpacing(d,id,lines){return replaceBlock(d,id,b=>b.type==='spacing'?{...b,lines:Math.max(1,Math.min(8,Number(lines)||1))}:b);}
export function mergePrevious(d,id){const i=idx(d,id);if(i<=0)return{doc:d,focusId:id,offset:0};const a=d.blocks[i-1],b=d.blocks[i];if(a.type==='spacing')return{doc:{...d,blocks:d.blocks.filter((_,n)=>n!==i-1)},focusId:b.id,offset:0};if(a.type==='divider'||b.type==='divider'||typeof a.text!=='string'||typeof b.text!=='string')return{doc:d,focusId:id,offset:0};const offset=a.text.length;const blocks=d.blocks.map((x,n)=>n===i-1?{...a,text:a.text+b.text}:x).filter((_,n)=>n!==i);return{doc:{...d,blocks},focusId:a.id,offset};}
export function ensureEditableNeighbors(d,id){const original=idx(d,id);if(original<0)return d;const blocks=[...d.blocks];let i=original;if(i===0||blocks[i-1].type!=='paragraph'){blocks.splice(i,0,createBlock('paragraph',{structural:true}));i++;}if(i===blocks.length-1||blocks[i+1].type!=='paragraph')blocks.splice(i+1,0,createBlock('paragraph',{structural:true}));return{...d,blocks};}
export function changeType(d,id,type,o={}){const b=d.blocks.find(x=>x.id===id);if(!b)return d;if(type==='divider')return replaceBlock(d,id,()=>createBlock('divider',{id}));if(type==='list')return replaceBlock(d,id,()=>createBlock('list',{id,style:o.style}));if(type==='heading')return replaceBlock(d,id,()=>createBlock('heading',{id,text:b.text||'',size:o.size||2}));return replaceBlock(d,id,()=>createBlock(type,{id,text:b.text||'',credit:b.credit||''}));}
function cleanListText(value){return String(value||'').replace(/<\\/?(?:div|p|br|span)[^>]*>/gi,'').replace(/[\\r\\n]/g,'');}
export function updateListItem(d,blockId,itemId,patch){return replaceBlock(d,blockId,b=>({...b,items:b.items.map(i=>i.id===itemId?{...i,...patch,text:patch.text===undefined?i.text:cleanListText(patch.text)}:i)}));}
export function splitListItem(d,blockId,itemId,offset){const b=d.blocks.find(x=>x.id===blockId);const i=b?.items.findIndex(x=>x.id===itemId);if(!b||b.type!=='list'||i<0)return{doc:d,nextItemId:null};const item=b.items[i],value=cleanListText(item.text),safeOffset=Math.max(0,Math.min(value.length,Number(offset)||0)),next={id:crypto.randomUUID(),text:value.slice(safeOffset),checked:false},items=[...b.items];items[i]={...item,text:value.slice(0,safeOffset)};items.splice(i+1,0,next);return{doc:replaceBlock(d,blockId,x=>({...x,items})),nextItemId:next.id};}
export function removeListItem(d,blockId,itemId){const b=d.blocks.find(x=>x.id===blockId);if(!b||b.type!=='list')return d;if(b.items.length===1)return removeBlock(d,blockId);return replaceBlock(d,blockId,x=>({...x,items:x.items.filter(i=>i.id!==itemId)}));}
