import React,{useEffect,useState}from'react';
import RichEditor from'../editor/RichEditor.jsx';import ProfilePage from'../profile/ProfilePage.jsx';
import {configureTelegramNavigation,getTelegramUser,initTelegramWebApp,setTelegramNavigation}from'../telegram/webApp.js';
import{loadChannels}from'../channels/channelStorage.js';import{postTelegram}from'../telegram/api.js';import{Send,UserRound}from'lucide-react';

function Avatar({user}){const[fallback,setFallback]=useState(false);return user?.photo_url&&!fallback?<img src={user.photo_url} className="user-avatar" alt="" onError={()=>setFallback(true)}/>:<span className="user-avatar fallback"><UserRound size={19}/></span>;}
function SendSheet({document,onClose}){const[channels,setChannels]=useState([]),[busy,setBusy]=useState(false);useEffect(()=>{loadChannels().then(setChannels).catch(()=>{})},[]);async function send(target){setBusy(true);try{await postTelegram('sendRichMessage',{document,target});onClose();}catch(e){alert(e.message)}finally{setBusy(false)}}return <div className="sheet-backdrop" onClick={onClose}><div className="send-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><b>Send Rich Message</b><button disabled={busy} onClick={()=>send({type:'private'})}><UserRound size={18}/><span>Test in Private Chat<small>Send to yourself first</small></span></button>{channels.map(c=><button disabled={busy} key={String(c.id)} onClick={()=>send({type:'channel',chat_id:c.id})}><span className="channel-mini-icon">{(c.title||'C')[0]}</span><span>{c.title||c.username||c.id}<small>{c.username?'@'+c.username:c.id}</small></span></button>)}{!channels.length&&<p className="hint">No saved channels yet. Add one from your profile.</p>}</div></div>}

export default function App(){const[page,setPage]=useState('editor'),[sendDoc,setSendDoc]=useState(null),user=getTelegramUser();useEffect(()=>{initTelegramWebApp();return configureTelegramNavigation({onBack:()=>setPage('editor'),onSettings:()=>setPage('profile')})},[]);useEffect(()=>{setTelegramNavigation({showBack:page==='profile',showSettings:page==='editor'})},[page]);if(page==='profile')return <ProfilePage/>;return <div className="app"><RichEditor onSend={setSendDoc}/><button className="profile-button" onClick={()=>setPage('profile')} aria-label="Open profile"><Avatar user={user}/></button>{sendDoc&&<SendSheet document={sendDoc} onClose={()=>setSendDoc(null)}/>}</div>}
