import React,{useEffect,useRef,useState}from'react';
import{ChevronDown,Hash,Info,Plus,Save,ShieldCheck,Trash2,UserRound,XCircle}from'lucide-react';
import{getTelegramUser,telegramHaptic,telegramImpact}from'../telegram/webApp.js';import{postTelegram}from'../telegram/api.js';import{loadChannels,removeChannel,saveChannel}from'../channels/channelStorage.js';

function Avatar({user}){const[fallback,setFallback]=useState(false);return user?.photo_url&&!fallback?<img src={user.photo_url} className="profile-avatar" alt="" onError={()=>setFallback(true)}/>:<div className="profile-avatar fallback"><UserRound size={32}/></div>;}
function friendlyError(error){const message=String(error?.message||'').trim();if(!message)return'We could not verify this channel. Please try again.';if(/chat not found|username not found|chat_id is empty|channel username is invalid/i.test(message))return'We could not find that channel. Check the @username or numeric channel ID and try again.';if(/administrator|admin/i.test(message))return'Add this bot as an administrator in the channel, then try again.';if(/permission|can.?post|not enough rights/i.test(message))return'The bot is an administrator, but it cannot post messages. Give it permission to post messages and try again.';if(/not a channel/i.test(message))return'That chat is not a channel. Enter a channel @username or channel ID.';if(/storage/i.test(message))return'Your Telegram storage is unavailable right now. Reopen the Mini App in Telegram and try again.';return message.replace(/^Bad Request:\s*/i,'')||'We could not verify this channel. Please try again.';}
export default function ProfilePage(){const u=getTelegramUser(),name=[u?.first_name,u?.last_name].filter(Boolean).join(' ')||'Telegram User',[channels,setChannels]=useState([]),[expanded,setExpanded]=useState(false),[id,setId]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(null),[defaultId,setDefaultId]=useState('');const inputRef=useRef(null);
useEffect(()=>{loadChannels().then(x=>{setChannels(x);if(x[0])setDefaultId(String(x[0].id))}).catch(()=>{})},[]);
function showError(message){setMsg({type:'error',text:message});telegramHaptic('error');}
function showSuccess(message){setMsg({type:'success',text:message});telegramHaptic('success');}
async function verify(){if(!id.trim()){showError('Enter a channel @username or numeric channel ID first.');inputRef.current?.focus();return}setBusy(true);setMsg(null);telegramImpact('light');try{const r=await postTelegram('verifyChannel',{channel_id:id.trim()});const next=await saveChannel(r.channel);setChannels(next);setDefaultId(String(r.channel.id));setId('');showSuccess('Channel verified and saved successfully.')}catch(e){showError(friendlyError(e))}finally{setBusy(false)}}
function addAnother(){setMsg(null);setExpanded(true);requestAnimationFrame(()=>inputRef.current?.focus());telegramImpact('light');}
async function remove(id){try{const x=await removeChannel(id);setChannels(x);if(String(defaultId)===String(id))setDefaultId(x[0]?String(x[0].id):'');setMsg({type:'success',text:'Channel removed.'});telegramHaptic('success')}catch(e){showError(friendlyError(e))}}
return <section className="page"><div className="profile-content"><h1 className="profile-title">Profile</h1><div className="profile-card"><Avatar user={u}/><div className="profile-name">{name}</div>{u?.username&&<div className="hint">@{u.username}</div>}<div className="hint">ID {u?.id||'—'}</div></div>
<section className={'settings-card channels-panel '+(expanded?'expanded':'')}><button className="settings-row channel-toggle" onClick={()=>{setExpanded(x=>!x);setMsg(null);telegramImpact('light')}} aria-expanded={expanded}><span className="row-icon"><Hash size={20}/></span><span className="row-copy"><b>Posting Channels</b><small>{channels.length?channels.length+' channel'+(channels.length===1?'':'s')+' configured':'Verify and manage publishing channels'}</small></span><ChevronDown size={19} className="chevron"/></button>
<div className="expand-content"><div className="channel-form"><div className="form-label">Add a channel</div><div className="input-wrap"><Hash size={17}/><input ref={inputRef} className="text-input" value={id} onChange={e=>setId(e.target.value)} placeholder="-1001234567890 or @channel" autoCapitalize="none" autoCorrect="off"/></div><button className="primary-button" onClick={verify} disabled={busy}>{busy?'Verifying…':<><Save size={17}/>Verify & Save</>}</button>{msg&&<div className={'status-note '+msg.type}>{msg.type==='error'?<XCircle size={16}/>:<ShieldCheck size={16}/>}<span>{msg.text}</span></div>}</div>
<div className="saved-heading"><span>Saved channels</span><span>{channels.length}</span></div>{!channels.length&&<div className="empty-state"><Info size={17}/><span>No channels saved yet. Verify one above to add it.</span></div>}{channels.map(c=><div className="channel-row" key={String(c.id)}><label className="channel-select"><input type="radio" name="default-channel" checked={String(defaultId)===String(c.id)} onChange={()=>{setDefaultId(String(c.id));telegramImpact('light')}}/><span className="radio-dot"/><div className="channel-avatar">{(c.title||'C')[0]}</div><span><b>{c.title||c.username||c.id}</b><small>{c.username?'@'+c.username:c.id}</small></span></label><button className="remove-button" onClick={()=>remove(c.id)} aria-label="Remove channel"><Trash2 size={17}/></button></div>)}{channels.length>0&&<button className="add-channel-button" onClick={addAnother}><Plus size={17}/>Add another channel</button>}<div className="channel-hint"><Info size={16}/><span>Add the bot as an administrator in your channel and allow it to post messages before verifying.</span></div></div></section></div></section>}

